### ISSUE TITLE
Pinout and touchscreen

### ISSUE THREAD

**Issue by RaresAil** [cowchimp/rpi-ili9341-lcd#1]
Hey, does this package supports also the touchscreen and is there a schematic on how to connect the pins?

**Comment by cowchimp** [comment]
> Hey, does this package supports also the touchscreen and is there a schematic on how to connect the pins?

Hi.
I only tested this against this product https://www.waveshare.com/wiki/2.4inch_LCD_Module which does not have a touchscreen (this page also has a diagram on how to connect the pins).

**Comment by RaresAil** [comment]
Thanks!
